title: Iyin Raphael # your name (or website title) here
logo: "/images/pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  After about 7+ years careeer in Geographic Informations Systems(GIS).
  I decided to start a new journey studying iOS development in <a href="https://www.lambdaschool.com/">Lambda School</a>
  In 1 year I gained solid experience in iOS Engineering with Swift and Objective-C.
  I also had the opportunity to be a Class Lead for new cohorts because of my exceptional effort.
  <br><br>
  
    I am a hard-working , with the ability to solve problems and think critically.
    I have a good  interpersonal communication skills, can adapt and learn in a fast paced environment"
    Looking for full-time opportunities.
    
  <br><br>
  <a href="https://www.github.com/iyinraphael/">
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
